package try

func (e *exceptionInteractor) GetException() any {
	return e.exception
}
